enum Permission {
    VIEW_ROLES = 'VIEW_ROLES',
    DELETE_ROLES = 'DELETE_ROLES',
    UPDATE_ROLES = 'UPDATE_ROLES',
    ADD_ROLES = 'ADD_ROLES',
    GIVE_ROLE = 'GIVE_ROLE',
    REMOVE_ROLE = 'REMOVE_ROLE',

    VIEW_USERS = 'VIEW_USERS',
    UPDATE_USERS = 'UPDATE_USERS',

    VIEW_EVENTS = 'VIEW_EVENTS',
    UPDATE_EVENTS = 'UPDATE_EVENTS',
    DELETE_EVENTS = 'DELETE_EVENTS',
    ADD_EVENTS = 'ADD_EVENTS',
}

export default Permission;
