enum Permission {
    VIEW_USERS = "VIEW_USERS",
    MANAGE_USERS = "MANAGE_USERS",

    VIEW_MEETINGS = "VIEW_MEETINGS",
    MANAGE_MEETINGS = "MANAGE_MEETINGS",

    VIEW_ROLES = "VIEW_ROLES",
    MANAGE_ROLES = "MANAGE_ROLES"
}

export default Permission;
